baseURL = "https://toribiodiego.github.io/"
title = "Diego Toribio"
theme = "hugo-bearblog"
languageCode = "en-us"
mainSections = ["Writing"]   # tells the theme which section is your blog

[pagination]
  pagerSize = 10

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions]
  footnote = true

[taxonomies]
  portfolio_tag = "portfolio_tags"
  writing_tag = "writing_tags"
